# Generated by Django 3.0.4 on 2020-03-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200327_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('test permissions1', 'test permissions2'),), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
